services:
  - type: web
    name: static-web
    runtime: static
    buildCommand: "pip install -r requirements.txt"
    startCommand: "py main.py"
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production